### ISSUE TITLE
Run fails when ssh not installed

### ISSUE THREAD

**Issue by edlins** [ansible-lockdown/UBUNTU18-STIG#6]
**Describe the Issue**
Does not work without `ssh` package, does not respect `ubtu18stig_ssh_required: false`

**Expected Behavior**
All tasks relating to `ssh` should be skipped.

**Actual Behavior**
```
TASK [/home/user/UBUNTU18-STIG : HIGH | UBTU-18-010412 | PATCH | The Ubuntu operating system must enforce SSHv2 for network access to all accounts.] 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Destination /etc/ssh/sshd_config does not exist !", "rc": 257}
```

**Control(s) Affected**
010412
010420
010424
010411
010414
010415
010416
010417
010418
010419
010512
and possibly more, I gave up here.

**Environment (please complete the following information):**

- `devel` (==`main`)
- Ansible Version: `2.9.27`
- Host Python Version: `2.7.17` (old, I know)
- Ansible Server Python Version: `2.7.17`
- Additional Details:
Ubuntu Desktop 18.04.5 LTS
`ssh` package NOT installed

**Additional Notes**
Steps to reproduce:

- `git clone https://github.com/ansible-lockdown/UBUNTU18-STIG`
- `sed -i 's/ubtu18stig_ssh_required: true/ubtu18stig_ssh_required: false/' UBUNTU18-STIG/defaults/main.yml`
- `ansible-playbook -D UBUNTU18-STIG/site.yml -i localhost, --connection=local -e "ansible_become_password=[password]" | tee stig.txt`

**Possible Solution**
I ran these to get past the 10 failing tasks.
```
sed -i '/ubtu_18_010412/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat1.yml
sed -i '/ubtu_18_010420/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat1.yml
sed -i '/ubtu_18_010424/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat1.yml
sed -i '/ubtu_18_010411/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010414/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010415/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010416/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010417/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010418/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
sed -i '/ubtu_18_010419/a\      - ubtu18stig_ssh_required' UBUNTU18-STIG/tasks/fix-cat2.yml
```
But after all of that I still get this
```
TASK [/home/user/UBUNTU18-STIG : MEDIUM | UBTU-18-010512 | PATCH | The Ubuntu operating system must configure the uncomplicated firewall to rate-limit impacted network interfaces. | limit on service] *********************************************************************************************
failed: [localhost] (item=OpenSSH) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw --version", "/usr/sbin/ufw limit from any to any app 'OpenSSH'"], "item": "OpenSSH", "msg": "ERROR: Could not find a profile matching 'OpenSSH'\n"}
```
I gave up at that point and resolved it with
```
sudo apt-get install -y ssh
```
It seems that this is just not setup to run on a system without `ssh`.

**Comment by MrSteve81** [comment]
Sorry for the delay in this taking a look at it today and will address it.

**Comment by MrSteve81** [comment]
This will be fixed in the upcoming release for v2r10 and that option will be removed, this was artifact from a old release.  If you would like to run the playbook you can either shut off the controls in the default/main file, or run your playbook ansible-playbook example.yml --skip-tags "ssh"
