### ISSUE TITLE
Run fails on systems with snap gnome-system-monitor

### ISSUE THREAD

**Issue by edlins** [ansible-lockdown/UBUNTU18-STIG#7]
**Describe the Issue**
When the task for `Set home perms` runs, it finds a link to a folder on a read-only filesystem and fails with `OSError: [Errno 30] Read-only file system`

**Expected Behavior**
Links to different filesystems outside of the home dir fs should not be followed or modified.

**Actual Behavior**
```
TASK [/home/user/UBUNTU18-STIG : MEDIUM | UBTU-18-010451 | PATCH | All local interactive user home directories must have mode 0750 or less permissive. | Set home perms] 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 30] Read-only file system: '/snap/gnome-system-monitor/174/data-dir/themes'
```

**Control(s) Affected**
010451

**Environment (please complete the following information):**

- branch being used: `devel` (==`main`)
- Ansible Version: `2.9.27`
- Host Python Version: `2.7.17` (old, I know)
- Ansible Server Python Version: `2.7.17`
- Additional Details:
Ubuntu Desktop 18.04.05 LTS
snap gnome-system-monitor 42 installed
```
snap list gnome-system-monitor
Name                  Version  Rev  Tracking         Publisher   Notes
gnome-system-monitor  42.0     181  latest/stable/…  canonical✓  -
```

**Additional Notes**
The `find` command has `-not -type l` which correctly finds `/home/[user]/snap/gnome-system-monitor/174/`.
But that folder contains a link to a read-only filesystem
```
ls -al /home/[user]/snap/gnome-system-monitor/174/
total 20
drwxr-xr-x 4 user user 4096 Feb  1  2022 .
drwxr-x--- 5 user user 4096 Oct 21 10:10 ..
drwx------ 7 user user 4096 Feb  1  2022 .config
-rw-rw-r-- 1 user user   31 Feb  1  2022 .last_revision
drwxr-x--- 3 user user 4096 Feb  1  2022 .local
lrwxrwxrwx 1 user user   46 Feb  1  2022 .themes -> /snap/gnome-system-monitor/174/data-dir/themes
```
And then it tries to change permissions on `/snap/gnome-system-monitor/174/data-dir/themes` which will never succeed because all `/snap/` subdirs are mounted `ro`.
```
mount | grep /snap/gnome-system-monitor/174
/var/lib/snapd/snaps/gnome-system-monitor_174.snap on /snap/gnome-system-monitor/174 type squashfs (ro,nodev,relatime,x-gdu.hide)
```

**Possible Solution**
More careful conditional construction of `ubtu_18_010451_audit.results`??

**Comment by MrSteve81** [comment]
Sorry for the delay in this, taking a look at it today and will address it.

**Comment by MrSteve81** [comment]
Upon trying to replicate your you error I could not.  I am testing on a ubuntu18 box with the snap gnome-system-monitor installed and mine is not producing the error you have gotten.  Will continue to look into it today when i have some free time.

**Comment by uk-bolly** [comment]
hi @edlins 

Thank you again for raising this issue. It has taken longer than expected to get to this (client priorities), we have added a new fix which should resolve the problem you are seeing.
I am not sure if this is still an issue for you?

I will close this issue as it has been open for some time, please feel free to reopen if this is still outstanding.

many thanks

uk-bolly
